apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stars.cnstar.kubecto-kubernetes.info
spec:
  group: cnstar.kubecto-kubernetes.info
  names:
    kind: Star
    plural: stars
    singular: star
    shortNames:
    - st
    categories:
    - all   
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
  additionalPrinterColumns:
  - name: Schedule
    type: string
    description: schedule the program
    JSONPath: .spec.schedule
  - name: Command
    type: string
    description: The command
    JSONPath: .spec.command
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Phase
    type: string
    JSONPath: .spec.phase
