apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stars.cnstar.kubecto-kubernetes.info
spec:
  group: cnstar.kubecto-kubernetes.info
  names:
    kind: Star
    plural: stars
    singular: star
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
